name: Run Salida Job

on:
  schedule:
    # Lunes a jueves a las 19:00 (22:00 UTC)
    - cron: '0 22 * * 1-4'
    # Viernes a las 18:00 (21:00 UTC)
    - cron: '0 21 * * 5'
  workflow_dispatch:

jobs:
  selenium:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Docker image
        run: docker build -t geo_salida .

      - name: Run Salida Job
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: docker run -e USERNAME="${{ secrets.USERNAME }}" -e PASSWORD="${{ secrets.PASSWORD }}" geo_salida
